import './globals.css';
import type { Metadata } from 'next';
import { ShiftTypesProvider } from '@/contexts/shift-types-context';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className="font-sans">
        <ShiftTypesProvider>{children}</ShiftTypesProvider>
      </body>
    </html>
  );
}